import { Project, ContactInfo, MediumArticle } from './types';

export const CONTACT_INFO: ContactInfo = {
  phone: "(+254) 718-958-518",
  email: "rachaelkamau64@gmail.com",
  linkedin: "https://www.linkedin.com/in/rachael-kamau",
  medium: "https://medium.com/@rachaelkamau",
  github: "https://github.com/rachaelkamau-15",
  credly: "https://www.credly.com/users/rachael-kamau",
};

export const PROJECTS: Project[] = [
  {
    id: 'lemook-gardens',
    title: 'Lemook Gardens',
    description: 'A website for a garden destination that allows users to book reservations for dining, events, and accommodation.',
    category: 'Software Engineering',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/Lemook',
    liveUrl: 'https://lemookgardens.com/',
    tags: ['Web Development', 'Booking System', 'UI/UX'],
  },
  {
    id: 'genesis-pregnancy',
    title: 'Genesis Pregnancy Helper',
    description: 'A Flutter mobile app offering comprehensive pregnancy information for confident childbirth preparation.',
    category: 'Software Engineering',
    imageUrl: 'https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/pregancy_helper',
    tags: ['Flutter', 'Mobile App', 'HealthTech'],
  },
  {
    id: 'trisecure-solutions',
    title: 'Trisecure Solutions',
    description: 'Information Technology (IT) Services Website for digital safety and skills.',
    category: 'Software Engineering',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/TriSec-website.git',
    liveUrl: 'https://www.trisecuresolutions.co.ke',
    tags: ['IT Services', 'Web Design', 'Business'],
  },
  {
    id: 'pine-city-zoo',
    title: 'Pine City Zoo APP',
    description: 'An app showcasing animals found in the zoo, built using HTML and CSS for a simple, informative experience.',
    category: 'Software Engineering',
    imageUrl: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/Pine-City-Zoo',
    tags: ['HTML', 'CSS', 'Education'],
  },
  {
    id: 'maternal-health',
    title: 'Maternal Health Website',
    description: 'Website focused on maternal healthcare. Built with HTML, CSS, JavaScript, PHP and MySQL.',
    category: 'Software Engineering',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/Genesis_Maternal',
    liveUrl: 'https://genesismaternal.netlify.app/',
    tags: ['PHP', 'MySQL', 'JavaScript', 'Health'],
  },
  {
    id: 'kenya-trivia',
    title: 'Kenya Trivia Game',
    description: 'Built a trivia game using Python to enhance knowledge about Kenya.',
    category: 'Software Engineering',
    imageUrl: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/python_kibo_project',
    tags: ['Python', 'Game Development', 'Education'],
  },
  {
    id: '2fa-implementation',
    title: 'Two-Factor Authentication (2FA)',
    description: 'Implementation in Python applications to strengthen security by requiring an extra verification step beyond passwords.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/FUTURE_CS_01',
    tags: ['Python', 'Security', 'Authentication'],
  },
  {
    id: 'firewall-setup',
    title: 'Firewall Setup (UFW)',
    description: 'A guide on setting up a firewall on Kali Linux using Uncomplicated Firewall (UFW) for enhanced system security.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/FUTURE_CS_02',
    tags: ['Kali Linux', 'UFW', 'Network Security'],
  },
  {
    id: 'password-manager',
    title: 'Secure Password Manager',
    description: 'A simple Python-based Password Manager that uses hashed passwords to ensure security and prevents plain-text storage.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&q=80&w=800&h=600',
    githubUrl: 'https://github.com/rachaelkamau-15/FUTURE_CS_03',
    tags: ['Python', 'Encryption', 'Security'],
  },
  {
    id: 'partyrock-simulator',
    title: 'AI Cybersecurity Simulator',
    description: 'Developed an AI-powered simulator using PartyRock to create interactive cybersecurity awareness training scenarios.',
    category: 'Cloud Security',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800&h=600',
    liveUrl: 'https://partyrock.aws/u/rahil2/XtudHOV4m/Cyber-Mjanja-Kuwa-Mjanja-Kuwa-Salama',
    tags: ['AI', 'Cloud Security', 'Awareness'],
  },
  {
    id: 'aws-s3-static',
    title: 'How to Host A Static Website Using AWS S3',
    description: 'A comprehensive guide on hosting highly available and scalable static websites using Amazon S3 buckets.',
    category: 'Cloud Security',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl:'https://medium.com/@rachaelkamau/how-to-host-a-static-website-using-aws-s3-01267a5fb7c4',
    tags: ['AWS', 'S3', 'Cloud Hosting'],
  },
  {
    id: 'aws-iam-guide',
    title: 'From Zero to Access: Creating AWS Users and Assigning Groups Like a Pro!',
    description: 'Mastering AWS IAM by setting up users, groups, and policies for secure access management.',
    category: 'Cloud Security',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl: 'https://medium.com/@rachaelkamau/from-zero-to-access-creating-aws-users-and-assigning-groups-like-a-pro-c136dbc17f05',
    tags: ['AWS', 'IAM', 'Security'],
  },
  {
    id: 'aws-ec2-setup',
    title: 'Create EC2 Instance in AWS (Amazon)',
    description: 'Step-by-step implementation of virtual servers in the cloud using Amazon EC2.',
    category: 'Cloud Security',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl: 'https://medium.com/@rachaelkamau/create-ec2-instance-in-aws-amazon-22df80349160',
    tags: ['AWS', 'EC2', 'Cloud Computing'],
  },
  {
    id: 'sql-injection-lab',
    title: 'SQL Injection: A Hands-On Guide Using PortSwigger’s Web Security Labs',
    description: 'Practical exploration of SQL injection vulnerabilities and mitigation techniques using industry-standard labs.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl: 'https://medium.com/@rachaelkamau/sql-injection-a-hands-on-guide-using-portswiggers-web-security-labs-c7926eb1f953',
    tags: ['SQLi', 'Web Security', 'PortSwigger'],
  },
  {
    id: 'osint-gathering',
    title: 'Unveiling Vulnerabilities: The Power of Information Gathering and OSINT in Cybersecurity',
    description: 'Leveraging Open Source Intelligence (OSINT) techniques for comprehensive reconnaissance and threat intelligence.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl: 'https://medium.com/@rachaelkamau/unveiling-vulnerabilities-the-power-of-information-gathering-and-osint-in-cybersecurity-2a97d8f55dff',
    tags: ['OSINT', 'Reconnaissance', 'Cyber Intelligence'],
  },
  {
    id: 'cisco-firewall',
    title: 'Basic Firewall Configuration in Cisco Packet Tracer',
    description: 'Designing and implementing network security policies using Cisco ASA firewalls in a simulated environment.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl: 'https://medium.com/@rachaelkamau/basic-firewall-configuration-in-cisco-packet-tracer-16e3f1aefef0',
    tags: ['Cisco', 'Packet Tracer', 'Firewall'],
  },
  {
    id: 'nmap-scan',
    title: 'Vulnerability Scan with Nmap',
    description: 'Using Nmap for network discovery and security auditing to identify open ports and potential vulnerabilities.',
    category: 'Cybersecurity',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800&h=600',
    mediumUrl: 'https://medium.com/@rachaelkamau/vulnerability-scan-with-nmap-ab50f343c271',
    tags: ['Nmap', 'Scanning', 'Security Audit'],
  },
];
